{
	"name": "02_ModelingDataflow",
	"ppdf:dataflowId": "5835f450-b0db-4d64-a64c-a49c59b554c9",
	"ppdf:owner": {
		"tenantId": "f77a80c9-6910-4bdc-b61b-817066d56b46",
		"userId": "d66f10cd-daab-40af-841c-0f1b49df5934"
	},
	"ppdf:fastCopy": false,
	"version": "1.0",
	"culture": "en-US",
	"modifiedTime": "2024-09-02T16:24:32.1055734+00:00",
	"ppdf:outputFileFormat": "Parquet",
	"pbi:mashup": {
		"fastCombine": false,
		"allowNativeQueries": true,
		"queriesMetadata": {
			"sets_forModelLayer": {
				"queryId": "e8ee1fd1-7fbc-419a-823a-de287f354219",
				"queryName": "sets_forModelLayer"
			},
			"inventory_parts_forModelLayer": {
				"queryId": "b39ec364-4af0-4fac-a73e-d45f2d94f41a",
				"queryName": "inventory_parts_forModelLayer"
			},
			"staging_parts": {
				"queryId": "f63511cb-48db-4e35-a093-e749d0692c43",
				"queryName": "staging_parts",
				"loadEnabled": true
			},
			"staging_themes": {
				"queryId": "86110f71-ea0c-4d01-ad47-215b66746bdb",
				"queryName": "staging_themes",
				"loadEnabled": true
			},
			"staging_parts_categories": {
				"queryId": "2ab991d8-9818-4bf5-87c2-70fafae27ed1",
				"queryName": "staging_parts_categories",
				"loadEnabled": true
			},
			"staging_inventories": {
				"queryId": "5b8c95ea-ad3b-430b-9128-bcb181bd74fa",
				"queryName": "staging_inventories",
				"loadEnabled": true
			},
			"staging_colors": {
				"queryId": "b4f6c91b-0edf-415d-9652-5c2204b062fa",
				"queryName": "staging_colors",
				"loadEnabled": true
			},
			"staging_elements": {
				"queryId": "463c5fea-6c47-44a3-b70b-5457c7f226ac",
				"queryName": "staging_elements",
				"loadEnabled": true
			},
			"sets_forModelLayer_DataDestination": {
				"queryId": "529f1802-2565-403a-908f-081fd43852a5",
				"queryName": "sets_forModelLayer_DataDestination"
			},
			"sets_forModelLayer_WriteToDataDestination": {
				"queryId": "66d454d1-a275-4437-996d-5dba7b43e497",
				"queryName": "sets_forModelLayer_WriteToDataDestination"
			},
			"sets_forModelLayer_TransformForWriteToDataDestination": {
				"queryId": "de9734e5-c5e5-421c-bad9-5566a0f7d6a4",
				"queryName": "sets_forModelLayer_TransformForWriteToDataDestination"
			},
			"inventory_parts_forModelLayer_DataDestination": {
				"queryId": "1a201dcf-36e3-4be4-8ede-b5dfca50bd2e",
				"queryName": "inventory_parts_forModelLayer_DataDestination"
			},
			"inventory_parts_forModelLayer_WriteToDataDestination": {
				"queryId": "7283f9a8-13f7-4cb4-8242-4c280020e50b",
				"queryName": "inventory_parts_forModelLayer_WriteToDataDestination"
			},
			"inventory_parts_forModelLayer_TransformForWriteToDataDestination": {
				"queryId": "c28a9241-e15e-4e00-be4c-ef9a57b1fed8",
				"queryName": "inventory_parts_forModelLayer_TransformForWriteToDataDestination"
			}
		},
		"document": "section Section1;\r\nshared sets_forModelLayer = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_sets\", ItemKind = \"Table\"]}[Data],\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Navigation 1\", {\"theme_id\"}, staging_themes, {\"id\"}, \"staging_themes\", JoinKind.LeftOuter),\r\n  #\"Expanded staging_themes\" = Table.ExpandTableColumn(#\"Merged queries\", \"staging_themes\", {\"parent_id\", \"name\"}, {\"parent_id\", \"name.1\"}),\r\n  #\"Merged queries 1\" = Table.NestedJoin(#\"Expanded staging_themes\", {\"parent_id\"}, staging_themes, {\"id\"}, \"staging_themes\", JoinKind.LeftOuter),\r\n  #\"Expanded staging_themes 1\" = Table.ExpandTableColumn(#\"Merged queries 1\", \"staging_themes\", {\"name\"}, {\"name.2\"}),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Expanded staging_themes 1\", \"parent_theme\", each if [name.2] = null then [name.1] else [name.2]),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Inserted conditional column\", {{\"name.1\", \"sub_theme\"}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Renamed columns\", {\"parent_id\", \"name.2\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed columns\", {{\"parent_theme\", type text}}),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Changed column type\", {\"theme_id\"})\r\nin\r\n  #\"Removed columns 1\";\r\nshared inventory_parts_forModelLayer = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_inventory_parts\", ItemKind = \"Table\"]}[Data],\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Navigation 1\", {\"inventory_id\"}, staging_inventories, {\"id\"}, \"staging_inventories\", JoinKind.LeftOuter),\r\n  #\"Expanded staging_inventories\" = Table.ExpandTableColumn(#\"Merged queries\", \"staging_inventories\", {\"version\", \"set_num\"}, {\"version\", \"set_num\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Expanded staging_inventories\", {{\"version\", \"inventory_version\"}}),\r\n  #\"Merged queries 1\" = Table.NestedJoin(#\"Renamed columns\", {\"part_num\"}, staging_parts, {\"part_num\"}, \"staging_parts\", JoinKind.LeftOuter),\r\n  #\"Expanded staging_parts\" = Table.ExpandTableColumn(#\"Merged queries 1\", \"staging_parts\", {\"name\", \"part_material\", \"part_category\"}, {\"name\", \"part_material\", \"part_category\"}),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Expanded staging_parts\", {{\"name\", \"part_name\"}}),\r\n  #\"Merged queries 2\" = Table.NestedJoin(#\"Renamed columns 1\", {\"color_id\"}, staging_colors, {\"id\"}, \"staging_colors\", JoinKind.LeftOuter),\r\n  #\"Expanded staging_colors\" = Table.ExpandTableColumn(#\"Merged queries 2\", \"staging_colors\", {\"name\", \"rgb\", \"is_trans\"}, {\"name\", \"rgb\", \"is_trans\"}),\r\n  #\"Renamed columns 2\" = Table.RenameColumns(#\"Expanded staging_colors\", {{\"name\", \"color_name\"}, {\"rgb\", \"color_rgb\"}, {\"is_trans\", \"color_is_trans\"}}),\r\n  #\"Merged queries 3\" = Table.NestedJoin(#\"Renamed columns 2\", {\"part_num\", \"color_id\"}, staging_elements, {\"part_num\", \"color_id\"}, \"staging_elements\", JoinKind.LeftOuter),\r\n  #\"Expanded staging_elements\" = Table.ExpandTableColumn(#\"Merged queries 3\", \"staging_elements\", {\"element_id\", \"design_id\"}, {\"element_id\", \"design_id\"}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Expanded staging_elements\", {\"color_id\"}),\r\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Removed columns\", \"Custom\", each if [is_spare] = \"t\" then \"Yes\" else \"No\"),\r\n  #\"Removed columns 1\" = Table.RemoveColumns(#\"Inserted conditional column\", {\"is_spare\"}),\r\n  #\"Renamed columns 3\" = Table.RenameColumns(#\"Removed columns 1\", {{\"Custom\", \"is_spare\"}}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Renamed columns 3\", {{\"is_spare\", type text}}),\r\n  #\"Inserted conditional column 1\" = Table.AddColumn(#\"Changed column type\", \"Custom\", each if [color_is_trans] = \"t\" then \"Yes\" else \"No\"),\r\n  #\"Removed columns 2\" = Table.RemoveColumns(#\"Inserted conditional column 1\", {\"color_is_trans\"}),\r\n  #\"Renamed columns 4\" = Table.RenameColumns(#\"Removed columns 2\", {{\"Custom\", \"color_is_trans\"}}),\r\n  #\"Changed column type 1\" = Table.TransformColumnTypes(#\"Renamed columns 4\", {{\"color_is_trans\", type text}})\r\nin\r\n  #\"Changed column type 1\";\r\nshared staging_parts = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_parts\", ItemKind = \"Table\"]}[Data],\r\n  #\"Merged queries\" = Table.NestedJoin(#\"Navigation 1\", {\"part_cat_id\"}, staging_parts_categories, {\"id\"}, \"staging_parts_categories\", JoinKind.LeftOuter),\r\n  #\"Expanded staging_parts_categories\" = Table.ExpandTableColumn(#\"Merged queries\", \"staging_parts_categories\", {\"name\"}, {\"name.1\"}),\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Expanded staging_parts_categories\", {{\"name.1\", \"part_category\"}}),\r\n  #\"Removed columns\" = Table.RemoveColumns(#\"Renamed columns\", {\"part_cat_id\"})\r\nin\r\n  #\"Removed columns\";\r\nshared staging_themes = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_themes\", ItemKind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared staging_parts_categories = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_parts_categories\", ItemKind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared staging_inventories = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_inventories\", ItemKind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared staging_colors = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_colors\", ItemKind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared staging_elements = let\r\n  Source = Lakehouse.Contents(null){[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data]{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  #\"Navigation 1\" = Source{[Id = \"staging_elements\", ItemKind = \"Table\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared sets_forModelLayer_DataDestination = let\r\n  Pattern = Lakehouse.Contents([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"obt_sets\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[set_num = nullable Text.Type, name = nullable Text.Type, year = nullable Int64.Type, num_parts = nullable Int64.Type, img_url = nullable Text.Type, sub_theme = nullable Text.Type, parent_theme = nullable Text.Type], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared sets_forModelLayer_WriteToDataDestination = let\r\n  sets_forModelLayer_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = sets_forModelLayer_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], sets_forModelLayer_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  sets_forModelLayer_WriteToDataDestination;\r\nshared sets_forModelLayer_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(sets_forModelLayer, {\"set_num\", \"name\", \"year\", \"num_parts\", \"img_url\", \"sub_theme\", \"parent_theme\"})\r\nin\r\n    SourceTable;\r\nshared inventory_parts_forModelLayer_DataDestination = let\r\n  Pattern = Lakehouse.Contents([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"eb49f716-7822-48aa-997c-075e178bac6b\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"f72b975e-ad75-43ae-a4d6-ad54f3e33ee1\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"obt_parts\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[inventory_id = nullable Int64.Type, part_num = nullable Text.Type, quantity = nullable Int64.Type, img_url = nullable Text.Type, inventory_version = nullable Int64.Type, set_num = nullable Text.Type, part_name = nullable Text.Type, part_material = nullable Text.Type, part_category = nullable Text.Type, color_name = nullable Text.Type, color_rgb = nullable Text.Type, element_id = nullable Int64.Type, design_id = nullable Int64.Type, is_spare = nullable Text.Type, color_is_trans = nullable Text.Type], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared inventory_parts_forModelLayer_WriteToDataDestination = let\r\n  inventory_parts_forModelLayer_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = inventory_parts_forModelLayer_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], inventory_parts_forModelLayer_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  inventory_parts_forModelLayer_WriteToDataDestination;\r\nshared inventory_parts_forModelLayer_TransformForWriteToDataDestination = let\r\n    SourceTable = Table.SelectColumns(inventory_parts_forModelLayer, {\"inventory_id\", \"part_num\", \"quantity\", \"img_url\", \"inventory_version\", \"set_num\", \"part_name\", \"part_material\", \"part_category\", \"color_name\", \"color_rgb\", \"element_id\", \"design_id\", \"is_spare\", \"color_is_trans\"})\r\nin\r\n    SourceTable;\r\n",
		"connectionOverrides": [
			{
				"path": "Lakehouse",
				"kind": "Lakehouse",
				"provider": "CdsA",
				"authenticationKind": null,
				"environmentName": null,
				"apiName": null,
				"connectionName": "{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}",
				"audience": null
			}
		]
	},
	"entities": [
		{
			"$type": "LocalEntity",
			"name": "staging_parts",
			"description": "",
			"pbi:refreshPolicy": {
				"$type": "FullRefreshPolicy",
				"location": "staging_parts.parquet"
			},
			"annotations": [
				{
					"name": "pbi:EntityTypeDisplayHint",
					"value": "CalculatedEntity"
				},
				{
					"name": "ppdf:entityKeys",
					"value": "[]"
				}
			],
			"attributes": [
				{
					"name": "part_num",
					"dataType": "string"
				},
				{
					"name": "name",
					"dataType": "string"
				},
				{
					"name": "part_material",
					"dataType": "string"
				},
				{
					"name": "part_category",
					"dataType": "string"
				}
			]
		},
		{
			"$type": "LocalEntity",
			"name": "staging_themes",
			"description": "",
			"pbi:refreshPolicy": {
				"$type": "FullRefreshPolicy",
				"location": "staging_themes.parquet"
			},
			"annotations": [
				{
					"name": "ppdf:entityKeys",
					"value": "[]"
				}
			],
			"attributes": [
				{
					"name": "id",
					"dataType": "int64"
				},
				{
					"name": "parent_id",
					"dataType": "int64"
				},
				{
					"name": "name",
					"dataType": "string"
				}
			]
		},
		{
			"$type": "LocalEntity",
			"name": "staging_parts_categories",
			"description": "",
			"pbi:refreshPolicy": {
				"$type": "FullRefreshPolicy",
				"location": "staging_parts_categories.parquet"
			},
			"annotations": [
				{
					"name": "ppdf:entityKeys",
					"value": "[]"
				}
			],
			"attributes": [
				{
					"name": "id",
					"dataType": "int64"
				},
				{
					"name": "name",
					"dataType": "string"
				}
			]
		},
		{
			"$type": "LocalEntity",
			"name": "staging_inventories",
			"description": "",
			"pbi:refreshPolicy": {
				"$type": "FullRefreshPolicy",
				"location": "staging_inventories.parquet"
			},
			"annotations": [
				{
					"name": "ppdf:entityKeys",
					"value": "[]"
				}
			],
			"attributes": [
				{
					"name": "id",
					"dataType": "int64"
				},
				{
					"name": "version",
					"dataType": "int64"
				},
				{
					"name": "set_num",
					"dataType": "string"
				}
			]
		},
		{
			"$type": "LocalEntity",
			"name": "staging_colors",
			"description": "",
			"pbi:refreshPolicy": {
				"$type": "FullRefreshPolicy",
				"location": "staging_colors.parquet"
			},
			"annotations": [
				{
					"name": "ppdf:entityKeys",
					"value": "[]"
				}
			],
			"attributes": [
				{
					"name": "id",
					"dataType": "int64"
				},
				{
					"name": "name",
					"dataType": "string"
				},
				{
					"name": "rgb",
					"dataType": "string"
				},
				{
					"name": "is_trans",
					"dataType": "string"
				}
			]
		},
		{
			"$type": "LocalEntity",
			"name": "staging_elements",
			"description": "",
			"pbi:refreshPolicy": {
				"$type": "FullRefreshPolicy",
				"location": "staging_elements.parquet"
			},
			"annotations": [
				{
					"name": "ppdf:entityKeys",
					"value": "[]"
				}
			],
			"attributes": [
				{
					"name": "element_id",
					"dataType": "int64"
				},
				{
					"name": "part_num",
					"dataType": "string"
				},
				{
					"name": "color_id",
					"dataType": "int64"
				},
				{
					"name": "design_id",
					"dataType": "int64"
				}
			]
		}
	]
}